name: 'trino_utils_dbt_project_evaluator_integration_tests'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'integration_tests'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

dispatch:
  - macro_namespace: dbt
    search_order: ['trino_utils_dbt_project_evaluator_integration_tests', 'trino_utils', 'dbt_project_evaluator', 'dbt']
  - macro_namespace: dbt_project_evaluator
    search_order: ['trino_utils_dbt_project_evaluator_integration_tests', 'trino_utils', 'dbt_project_evaluator']

models:
  trino_utils_dbt_project_evaluator_integration_tests:
    # materialize as ephemeral to prevent the fake models from executing, but keep them enabled
    +materialized: ephemeral
  dbt_project_evaluator_integration_tests:
    # materialize as ephemeral to prevent the fake models from executing, but keep them enabled
    +materialized: ephemeral
    marts:
      intermediate:
        to_exclude:
          # Overridden by trino_utils_dbt_project_evaluator_integration_tests to_exclude
          +enabled: false
      fct_model_6:
        +materialized: table
  dbt_project_evaluator:
    marts:
      tests:
        fct_test_coverage:
          # materialize as a table to ensure SQL query runs successfully
          +materialized: table
      documentation:
        fct_documentation_coverage:
          # materialize as a table to ensure SQL query runs successfully
          +materialized: table
      structure:
        # Overridden by trino__fct_model_naming_conventions
        fct_model_naming_conventions:
          +enabled: false
      dag:
        # Overridden by trino__fct_source_fanout
        fct_source_fanout:
          +enabled: false
        # Overridden by trino__fct_model_fanout
        fct_model_fanout:
          +enabled: false
        # Overridden by trino__fct_multiple_sources_joined
        fct_multiple_sources_joined:
          +enabled: false

tests:
  dbt_project_evaluator:
    +enabled: false
  dbt_project_evaluator_integration_tests:
    dag:
      # Overridden by trino__equality_fct_duplicate_sources
      equality_fct_duplicate_sources:
        +enabled: false
      # Overridden by trino__equality_fct_source_fanout
      equality_fct_source_fanout:
        +enabled: false
      # Overridden by trino__equality_fct_model_fanout
      equality_fct_model_fanout:
        +enabled: false
      # Overridden by trino__equality_fct_multiple_sources_joined
      equality_fct_multiple_sources_joined:
        +enabled: false
    structure:
      # Overridden by trino__equality_fct_model_naming_conventions
      equality_fct_model_naming_conventions:
        +enabled: false
    performance:
      # Overridden by trino__equality_fct_chained_views_dependencies
      equality_fct_chained_views_dependencies:
        +enabled: false

seeds:
  dbt_project_evaluator:
    dbt_project_evaluator_exceptions:
      +enabled: false
  dbt_project_evaluator_integration_tests:
    # Overridden by trino__dbt_project_evaluator_exceptions
    dbt_project_evaluator_exceptions:
      +enabled: false
    tests:
      # Overridden by trino__test_fct_test_coverage
      test_fct_test_coverage:
        +enabled: false
    docs:
      # Overridden by trino__test_fct_documentation_coverage
      test_fct_documentation_coverage:
        +enabled: false
    structure:
      # Overridden by trino__test_fct_model_naming_conventions
      test_fct_model_naming_conventions:
        +enabled: false
    dag:
      # Overridden by trino__test_fct_source_fanout
      test_fct_source_fanout:
        +enabled: false
      # Overridden by trino__test_fct_model_fanout
      test_fct_model_fanout:
        +enabled: false
      # Overridden by trino__test_fct_multiple_sources_joined
      test_fct_multiple_sources_joined:
        +enabled: false
    performance:
      # Overridden by trino__test_fct_chained_views_dependencies
      test_fct_chained_views_dependencies:
        +enabled: false

sources:
  dbt_project_evaluator_integration_tests:
    staging:
      source_1:
        # Overridden by trino__source_4
        source_3:
          +enabled: false

vars:
  # -- DAG variables --
  models_fanout_threshold: 3

  exclude_paths_from_project: ["/to_exclude/","trino__source_4.trino__table_6"]

  # -- Performance variables --
  chained_views_threshold: 3

  # -- Execution variables --
  max_depth_dag: 3
